services:

  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sleepmate"]
      interval: 5s
      retries: 5
      timeout: 5s


  backend:
    build: ./backend
    container_name: sleepmate_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

  bot:
    build: ./bot
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      retries: 5

  producer:
    build: ./notifications/producer
    restart: always
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy


  consumer:
    build: ./notifications/consumer
    restart: always
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
