"""v1 generate tables

Revision ID: 4520b7aef203
Revises:
Create Date: 2025-08-31 21:15:23.629151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4520b7aef203"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("morning_notification", sa.Time(), nullable=True),
        sa.Column("evening_notification", sa.Time(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True
    )
    op.create_table(
        "sleep_goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "goal_type",
            sa.Enum(
                "SLEEP_BEFORE", "WAKE_BEFORE", "SLEEP_HOURS", name="goaltype"
            ),
            nullable=False,
        ),
        sa.Column("value_time", sa.Time(), nullable=True),
        sa.Column("value_hours", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sleep_goals_id"), "sleep_goals", ["id"], unique=False
    )
    op.create_table(
        "sleep_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("bedtime", sa.Time(), nullable=False),
        sa.Column("wake_time", sa.Time(), nullable=False),
        sa.Column("sleep_quality", sa.Text(), nullable=True),
        sa.Column("feeling", sa.Text(), nullable=True),
        sa.Column("energy", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sleep_logs_id"), "sleep_logs", ["id"], unique=False
    )
    op.create_table(
        "sleep_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("week_start", sa.Date(), nullable=True),
        sa.Column("week_end", sa.Date(), nullable=True),
        sa.Column("short_summary", sa.Text(), nullable=False),
        sa.Column("long_summary", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sleep_reports_id"), "sleep_reports", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sleep_reports_id"), table_name="sleep_reports")
    op.drop_table("sleep_reports")
    op.drop_index(op.f("ix_sleep_logs_id"), table_name="sleep_logs")
    op.drop_table("sleep_logs")
    op.drop_index(op.f("ix_sleep_goals_id"), table_name="sleep_goals")
    op.drop_table("sleep_goals")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
